API_HOST_URL: 'http://localhost:8000'
ENVIRONMENT_DISPLAY_NAME: 'Localhost'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
OAUTH_CLIENT_ID: ''
OAUTH_CLIENT_SECRET: ''
SOCIAL_FEATURES_ENABLED: false
SEGMENT_IO_WRITE_KEY: ''
REGISTRATION_API_DEPRECATED: true
