API_HOST_URL: 'http://192.168.1.4:8000' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'Chris Machine'
PLATFORM_NAME: 'ChristopherX'
PLATFORM_DESTINATION_NAME: 'christopher.com'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
